# -*- coding: utf-8 -*-
"""NUMPY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zI1u3FPS56Ruh1_y_cvGw13yQI0NghDu

*NUMPY*
"""

import numpy as np
a = np.array([20,30,40])
b = np.array([50,60,70])
print(a)
print(b)
print(a+b)

a = np.array([20,30,40])
b = np.array (5)
print(a)
print(b)
print(a*b)

"""For Ex"""

l1 = [10,20,30]
l2 = 5
print(l1*l2)

"""These are concatenate each other like (join each other)"""

l1 = [10,20,30]
l2 = [50,40,30]
print(l1+l2)

"""*Array v/s List*
1. A list cannot directly handle mathematical operations, while Array can.
2. An Array consumes less memory than a list.
3. Using an Array is faster than list.
4. A list can store different datatype, while you can't do that in an Array.
5. A list is easier to modify since a list store each element individually, it is easier to add and delete an element than an array does.
6. In list one can have nested data with different size, while you cannot do the same in array.
"""

a = np.array([[20,30,10],[40,50,60]])
print(a)

arr = np.array([10,20,30])
print(arr)
print(type(arr))

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(arr)

"""**Slashing**

"""

arr = np.array([10,20,30,40])
print(arr[0:3])

arr = np.array([10,20,30,40])
print(arr[3:])

arr = np.array([10,20,30,40])
print(arr[:3])

arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:3])

arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0,1:3])

arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[1,2:4])

"""**Attributes of Array**"""

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr))

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr))
print(np.size(arr))

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

"""For Ex"""

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(np.dtype)

"""**Inspecting an Array**"""

a = [30,40,20,10,50]
arr = np.array(a)
print(arr)

a = [30,40,20],[40,30,10]
arr = np.array(a)
print(arr)
print(arr.shape)

a = [[30,40,20],[40,30,10]]
arr = np.array(a)
print(arr)
print(arr.shape) #rows, columns
print(len(arr)) #number of nested values
print(np.size(arr)) #number of elements
print(type(arr)) #number of variable
print(arr.dtype) #datatype of array
print(arr.astype(int)) #conversion of datatype

"""**Mathematical operations and functions of Arrays**"""

import numpy as np
arr1 = np.array([[30,40],[60,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1+arr2)

arr1 = np.array([[30,40],[60,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

arr1 = np.array([[30,40],[60,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

arr1 = np.array([[30,40],[60,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1*arr2)
print(np.divide(arr1,arr2))

arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print(np.power(arr1,arr2))

arr1 = np.array([9,16,4,1])
print(np.sqrt(arr1))

"""**Combination and Splitting Arrays**

This is concatenate each other.
"""

a = [30,40,50]
b = [5,5,3]
print(a+b)

"""But in numpy we use like this..."""

#Concatenate
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

print(np.concatenate([arr1,arr2],axis = 0))

arr1 = np.array([[30,40],[30,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2]))

print(np.concatenate([arr1,arr2],axis = 0))

print(np.hstack([arr1,arr2])) #Horizontal concatenation

print(np.vstack([arr1,arr2])) #Vertical concatenation

"""In case of Spliting the in two parts or other parts"""

a = np.array([20,40,30,40,10,20])
b = np.array_split(a,5)
print(b)

a = np.array([20,40,30,40,10,20])
b = np.array_split(a,4)
print(b)

"""**Adding & Removing Elements in the Arrays**

Append
"""

a = np.array([20,40,30])
print(np.append(a,50))

a = np.array([[20,30],[20,40]])
print(np.append(a,[50,60]))

"""Insert"""

print(np.insert(a,1,50)) #Array, Index, Value

print(np.insert(a,1,[50,60], axis = 0)) #Array, Index, Value

print(np.insert(a,[1,2],[50], axis = 0)) #Array, Index, Value

"""Delete"""

print(a)
print(np.delete(a,1))

print(a)
print(np.delete(a,1, axis = 0))

"""**Search, Sort & Filter Arrays**

**Sort**
"""

import numpy as np

ar = np.array([7,8,4,12,9])
print (np.sort(ar))

arr = np.array([[7,8,4,12,9],[2,4,3,7,5]])
print (np.sort(arr))

"""**Search**"""

arr = np.array([3,4,1,7,8])
s = np.where(arr == 4)
print(s)

arr = np.array([3,4,1,7,8])
s = np.where(arr % 2 == 0)
print(s)

"""**SearchSorted**"""

arr = np.array([1,2,3,4,5])
ss = np.searchsorted(arr,5)
print(ss)

"""*Filter*  <br>
To create an array through existing array..
"""

arr = np.array([20,30,50,60])
fa = [True, False, True, False]
new = arr[fa]
print(new)

arr = np.array([20,30,50,60])
fa = [True, False, False, False]
new = arr[fa]
print(new)

arr = np.array([20,30,50,60])
fa = arr>35
new = arr[fa]
print(new)

arr = np.array([20,30,50,60])
fa = arr<35
new = arr[fa]
print(new)

arr = np.array([2,3,4,5])
fa = arr%2 == 1
new = arr[fa]
print(new)

"""**Aggregating Function in Numpy**"""

a = np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.size(a))
print(np.prod(a))
print(np.cumprod(a))

"""*Example of cumulative product*"""

a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]
price = np.array(a)
quantity = np.array(b)
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]
price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)
print()
c = np.cumprod([price,quantity], axis = 0)
print(c[1].sum())

"""**Statistical Function in Arrays**"""

import statistics as stats
baked_food = [200,150,150,130,200,220,170,188]
a = np.array(baked_food)
print(np.mean(baked_food)) #Sum of all the values/number of values
print(np.median(baked_food)) #Cental value after sorting
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

"""**Co-Relation**"""

# - 1 represent inversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship
tabacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,122]
print(np.corrcoef([tabacco_consumption,deaths]))

price = [300,100,350,150,200]
sales = [10,20,7,17,3]
print(np.corrcoef([price,sales]))

import numpy as np

"""**Array Operations**

"""

# Scalar operations
arr1 = np.array([[30,40],[60,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1+arr2)

arr1*arr2

# max/min/sum/prod
np.max(arr1)

np.min(arr1)

np.sum(arr1)

np.prod(arr1)

# 0 -> col and 1 -> row
np.sum(arr1, axis = 0)

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

a1

a1[-1]

a2

a2[1,0]

a3

a3[1,0,1]

"""**Numpy array vs Python list**"""

#speed
#list
a = [i for i in  range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

"""Time diff^n because numpy use c type array in comparision to python list<br>
it is not refrencial array or in python daynamic array (app address nikal ka memory ma search karta ho usma additional time lagta hai)
"""

import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a + b
print(time.time()-start)

3.26/0.06

"""*89095160 bits occupy kar raha hai python ka list memory ma*"""

a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

"""**Adv indexing**"""

a = np.arange(24).reshape(6,4)
a

a[1,2]

a[1:3,1:3]

#fancy Indexing
a

a[[0,2,3,5]]

a[:,[0,2,3]]

#Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

# Find all numbers greater than 50
a > 50

a[a > 50]

# Find out even numbers
a % 2 == 0

a[a % 2 == 0]

# find all number greater than 50 and are even
(a > 50) & (a % 2 == 0)

a[(a > 50) & (a % 2 == 0)]

# find all number divisible by 7
a[~(a % 7 == 0)]

"""# Broadcasting
*The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.*<br>
*The smaller array is "broadcast" across the larger array so that they have compatible shapes.*
"""

# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)
print(a+b)

# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)
print(a+b)

"""# Broadcasting Rules
1. Make the two arrays have the same number of dimensions.<br>
    • If the number of dimensions of two arrays are different,add new dimensions with size 1 to the head of the array with the smaller dimension.  <br>
2. Make each dimension Of the two arrays the same size.<br>
    • If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.<br>
    • If there is a dimension whose size is not I in either of the two arrays, it cannot be broadcasted, and an error is raised.
   
"""

#Eg
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print(a+b)

a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

"""# Working with mathematical formulas"""

a = np.arange(10)
np.tan(a)

#Sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-array))

a = np.arange(10)
sigmoid(a)

def sigmoid(array):
  return 1/(1 + np.exp(-array))

a = np.arange(100)
sigmoid(a)

# mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

predicted

actual

def mse(actual,predicted):
  return np.mean((actual - predicted)**2)
mse(actual,predicted)

np.mean((actual - predicted)**2)

"""# Working with missing values"""

a = np.array([1,2,3,4,np.nan,6])
a

np.isnan(a)

a[~np.isnan(a)]

"""#plotting Graph"""

#plotting a 2D plot
# x = y
import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
y = x
plt.plot(x,y)

# y = x^2
x = np.linspace(-10,10,100)
y = x**2
plt.plot(x,y)

# y = sin(x)
x = np.linspace(-10,10,100)
y = np.sin(x)
plt.plot(x,y)

# y = tanx
x = np.linspace(10,-10,100)
y = np.tan(x)
plt.plot(x,y)

# log(x)
x = np.linspace(1,10,100)
y = np.log(x)
plt.plot(x,y)

# e^(-x)
x = np.linspace(1,10,100)
y = np.exp(-x)
plt.plot(x,y)

# sigmoid
x = np.linspace(-10,10,100)
y = 1/(1 + np.exp(-x))
plt.plot(x,y)

# cardiod
x = np.linspace(-10,10,100)
y = np.sinc(x)
plt.plot(x,y)

# Define theta from 0 to 2π
theta = np.linspace(0, 2 * np.pi, 500)

# Cardioid equation: r = 1 - cos(theta)
r = 1 - np.cos(theta)

# Convert polar to Cartesian
x = r * np.cos(theta)
y = r * np.sin(theta)

# Plot
plt.figure(figsize=(6,6))
plt.plot(x, y, color="red")
plt.title("Cardioid Curve: r = 1 - cos(θ)")
plt.xlabel("x")
plt.ylabel("y")
plt.axis("equal")  # Equal aspect ratio
plt.grid(True)
plt.show()

"""# np.sort


"""

#code
import numpy as np
a = np.random.randint(1,100,15)
a

b = np.random.randint(1,100,24).reshape(6,4)
b

np.sort(a)

np.sort(b)

"""# np.append
The numpy.append() append value along the mentioned axis at the end of the array
"""

#code
np.append(a,200)

b

np.append(b,np.random.random((b.shape[0],1)),axis=1)